VERZIJA=CDX
MODUL=MAT

SRCDOSROOT=$(BASEDOS)\\fmk\\mat\\exe\\
PRGS=e.prg

CS=
ASMS=

EOBJCOPY=echo nista za kopirati
FMK_LIBS=fmk_roba.lib fmk_svi.lib fmk_evn.lib fmk_sec.lib fmk_lok.lib fmk_rule.lib xmllib.lib 

SCLIB_LIBS=sc1g_arh.lib sc1g_ba.lib sc1g_cui.lib sc1g_db.lib sc1g_os.lib sc1g_ost.lib sc1g_par.lib sc1g_pr.lib sc1g_sif.lib sc1g_sql.lib sc1g_ut.lib sc2g_app.lib sc2g_db.lib sc1g_rpt.lib sc1g_key.lib sc2g_cui.lib sc_epl2.lib sc_gvp.lib ka_s1pf.lib

MODUL_LIBS=mat_db.lib mat_m.lib mat_rpt.lib mat_sif.lib mat_par.lib mat_rdb.lib mat_dok.lib


include ../../fmk_lib/Makefile_clipper

lib: exe

